### ISSUE TITLE
Replace the 'x' in `tabs.tsx` with an actual close icon

### ISSUE THREAD

**Issue by andrico1234** [andrico1234/sandpack-lit#1]
Currently I hardcode the letter 'x' inside of a button to close a tab. Update this to use a close icon instead

**Comment by RogueCode007** [comment]
hello @andrico1234 , I'd love to contribute.  Can I work on this ?

**Comment by andrico1234** [comment]
Absolutely! Go ahead. I haven't yet added contribution guidelines so if you need any help getting started, just ping me :) I'll try and some documentation in the coming days.

**Comment by RogueCode007** [comment]
> Absolutely! Go ahead. I haven't yet added contribution guidelines so if you need any help getting started, just ping me :) I'll try and some documentation in the coming days.

Great! I don't see any icon package in the package.json

> Absolutely! Go ahead. I haven't yet added contribution guidelines so if you need any help getting started, just ping me :) I'll try and some documentation in the coming days.

Great! I didn't see an icon library on package.json so I used an svg icon. Let me know if that's okay

**Comment by andrico1234** [comment]
Resolved in: https://github.com/andrico1234/sandpack-lit/issues/1
